# Baisc infomation
title: CTO+
description: > # this means to ignore newlines until "url:"
  CTO on Contract
url: "https://cto.plus/"
twitter_username: ctoplus
github_username:  ctoplus
github:
  is_project_page: false
  is_user_page: true
markdown: kramdown
show_downloads: false
google_analytics: UA-89931181-1
theme: jekyll-theme-architect
exclude:
  - Gemfile
  - Gemfile.lock
